version: '3'

services:   
  postgres: 
    image: 'postgres:latest'
    environment:
    # this is the default pasword for postgres
      - POSTGRES_PASSWORD=postgres_password
  redis: 
    image: 'redis:latest'
  api:
    # set the build context and dockerfile for dev
    build: 
      context: ./server
      dockerfile: Dockerfile.dev      
    volumes:
      # bookmark node_modules to the container so that it doesn't try to read from my local
      # node_modules folder
      - /app/node_modules
      # instead of copying the files to /app, the container will read it from my 
      # local server folder
      - ./server:/app
    
    # these are default ports, passwords, etc.
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
    # default redis values
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
  # we want the nginx server to always restart on failur since it sits
  # in front of the entire architecture
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    # this is the only service that will have port forwarding
    # visit 3050 locally to go to nginx port 80
    ports:
      - "3050:80"